[build]
  base = "PostWars"
  command = "npm ci && npm run build"
  publish = "PostWars/build"
  ignore = "*.sql,create-admin.js,.env*,SECURITY_AUDIT_REPORT.md"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "PostWars/build"

# Environment variables needed for deployment
# These should be set in Netlify dashboard:
# - PUBLIC_SUPABASE_URL
# - PUBLIC_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_KEY