[build]
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_ENABLED = "false"

# Secrets scanning configuration
[build.processing.secrets_scanning]
  enabled = false

# Environment variables needed for deployment
# These should be set in Netlify dashboard:
# - PUBLIC_SUPABASE_URL
# - PUBLIC_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_KEY