[build]
  command = "npm run build"
  functions = ".netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"


# Environment variables needed for deployment
# These should be set in Netlify dashboard:
# - PUBLIC_SUPABASE_URL
# - PUBLIC_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_KEY