[build]
  base = "PostWars"
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  SECRETS_SCAN_OMIT_KEYS = "PUBLIC_SUPABASE_URL,PUBLIC_SUPABASE_ANON_KEY"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "build"

# Redirects moved to _redirects file (required by SvelteKit adapter-netlify)

# Environment variables needed for deployment
# These should be set in Netlify dashboard:
# - PUBLIC_SUPABASE_URL
# - PUBLIC_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_KEY