[build]
  base = "PostWars"
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "build"

# Environment variables needed for deployment
# These should be set in Netlify dashboard:
# - PUBLIC_SUPABASE_URL
# - PUBLIC_SUPABASE_ANON_KEY  
# - SUPABASE_SERVICE_KEY