name: Update Goals

on:
  # Run twice daily at 5 AM and 5 PM Mountain Time (11 AM and 11 PM UTC)
  schedule:
    - cron: '0 11,23 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-goals:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Clean SvelteKit artifacts
      run: rm -rf .svelte-kit node_modules/.svelte-kit

    - name: Update goals
      env:
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
        PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
        NODE_ENV: production
      run: npm run cron:update-goals